# Generated by Django 4.2 on 2026-01-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('passcode', models.CharField(max_length=128)),
                ('dob', models.CharField(max_length=128)),
            ],
        ),
    ]
