# Generated by Django 4.2 on 2026-01-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='data',
            field=models.CharField(max_length=1000),
        ),
    ]
