# Generated by Django 4.2 on 2026-01-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_food_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='data',
            field=models.CharField(max_length=2000),
        ),
    ]
