# Generated by Django 4.2 on 2026-01-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_food_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='data',
        ),
        migrations.AddField(
            model_name='food',
            name='benefits',
            field=models.TextField(default='***', max_length=500),
        ),
        migrations.AddField(
            model_name='food',
            name='hazards',
            field=models.TextField(default='***', max_length=500),
        ),
        migrations.AddField(
            model_name='food',
            name='method',
            field=models.TextField(default='***', max_length=1000),
        ),
        migrations.AddField(
            model_name='food',
            name='nutrients',
            field=models.TextField(default='***', max_length=500),
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(default='***', max_length=64),
        ),
        migrations.AddField(
            model_name='food',
            name='variant',
            field=models.CharField(default='***', max_length=128),
        ),
        migrations.AlterField(
            model_name='food',
            name='item',
            field=models.CharField(default='***', max_length=128),
        ),
    ]
