# Generated by Django 5.2.10 on 2026-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_food_data_food_benefits_food_hazards_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['item', 'variant']},
        ),
        migrations.AlterField(
            model_name='food',
            name='benefits',
            field=models.TextField(blank=True, help_text='Health benefits', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='hazards',
            field=models.TextField(blank=True, help_text='Possible hazards or cautions', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='item',
            field=models.CharField(db_index=True, help_text='Main food item like Dosa, Idli', max_length=128),
        ),
        migrations.AlterField(
            model_name='food',
            name='method',
            field=models.TextField(blank=True, help_text='Detailed preparation method', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='nutrients',
            field=models.TextField(blank=True, help_text='Nutritional information', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(db_index=True, help_text='Category like breakfast, lunch, snack', max_length=64),
        ),
        migrations.AlterField(
            model_name='food',
            name='variant',
            field=models.CharField(db_index=True, help_text='Specific variant like Masala Dosa', max_length=128),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['item'], name='items_food_item_27e30d_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['variant'], name='items_food_variant_c62b69_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['type'], name='items_food_type_44499c_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['item', 'variant'], name='items_food_item_1d7653_idx'),
        ),
    ]
