# Generated by Django 5.2.10 on 2026-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_food_options_alter_food_benefits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='items_food_item_27e30d_idx',
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='items_food_variant_c62b69_idx',
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='items_food_type_44499c_idx',
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='items_food_item_1d7653_idx',
        ),
        migrations.AlterField(
            model_name='food',
            name='benefits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='hazards',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='item',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='food',
            name='method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='nutrients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='food',
            name='variant',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
