# Generated by Django 5.2.10 on 2026-01-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='food',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
