# Generated by Django 5.2.10 on 2026-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_food_source_url_food_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='type',
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='hazards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='nutrients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='variant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
