# Generated by Django 4.2 on 2026-01-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='passcode',
        ),
    ]
