# Generated by Django 4.2 on 2026-01-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_users_passcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='user',
        ),
    ]
