# Generated by Django 4.2 on 2026-01-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_email_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='***', max_length=128)),
                ('prompt', models.CharField(default='***', max_length=128)),
                ('bot', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=128, unique='True'),
        ),
    ]
