# Generated by Django 4.2 on 2026-01-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chats_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='bot',
            field=models.TextField(default='***'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
