# Generated by Django 4.2 on 2026-01-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_chats_bot_alter_users_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['count']},
        ),
        migrations.AddField(
            model_name='chats',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
