# Generated by Django 5.2.10 on 2026-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_chats_options_chats_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
